#! /bin/bash

set() {
  echo "Setting Themes..."
  gsettings set org.gnome.desktop.interface gtk-theme "$1"
  gsettings set org.gnome.desktop.interface accent-color "$2"
  gsettings set org.gnome.desktop.interface icon-theme "$3"

  echo "Linking Files..."
  ln ~/.themes/"$1"/gtk-4.0/assets ~/.config/gtk-4.0/assets -sf
  ln ~/.themes/"$1"/gtk-4.0/gtk.css ~/.config/gtk-4.0/gtk.css -sf
  ln ~/.themes/"$1"/gtk-4.0/gtk-dark.css ~/.config/gtk-4.0/gtk-dark.css -sf

  echo "Updating colorctl..."
  colorctl vars +accent-color=\#"$4"
  colorctl vars +accent-color-clean="$4"
  colorctl vars +waybar-color="$5"

  echo "Applying colorctl..."
  colorctl apply

  cat ~/.config/niri/pieces/* >~/.config/niri/config.kdl

}
case $1 in
"cpcn")
  ln ~/.config/waybar/colors/catppuccin-mocha.css ~/.config/waybar/colors.css -sf
  case $2 in
  "teal")
    set Catppuccin-Teal-Dark teal Adwaita-Teal 94e2d5 teal
    ;;
  "purple")
    set Catppuccin-Red-Dark purple Adwaita-Purple cba6f7 mauve
    ;;
  "red")
    set Catppuccin-Red-Dark red Adwaita-Red f38ba8 red
    ;;
  "green")
    set Catppuccin-Green-Dark green Adwaita-Green a6e3a1 green
    ;;
  "orange")
    set Catppuccin-Orange-Dark orange Adwaita-Orange fab387 peach
    ;;
  *)
    echo "Not a valid vairant"
    ;;
  esac
  ;;
"gruv")
  ln ~/.config/waybar/colors/gruvbox.css ~/.config/waybar/colors.css -sf
  case $2 in
  purple)
    set Gruvbox-Pink-Dark purple gruvbox_dark d3869b purple
    ;;
  aqua)
    set Gruvbox-Teal-Dark teal gruvbox_dark 689d6a aqua
    ;;
  orange)
    set Gruvbox-Orange-Dark orange gruvbox_dark fe8019 orange
    ;;
  green)
    set Gruvbox-Green-Dark green gruvbox_dark b8bb26 green
    ;;
  blue)
    set Gruvbox-Dark blue gruvbox_dark 458588 blue
    ;;
  red)
    set Gruvbox-Red-Dark red gruvbox_dark cc241d red
    ;;
  yellow)
    set Gruvbox-Yellow-Dark yellow gruvbox_dark d79921 yellow
    ;;
  *)
    echo "Not a valid vairant"
    ;;
  esac
  ;;

*)
  echo "Usage: accent {cpcn|gruv}"
  exit 1
  ;;
esac

~/projects/scripts/restart-waybar-hyprpaper waybar
