#! /bin/env python3
states = ["󰁻", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂀", "󰂂", "󰁹"]
power_level = -1
with open("/sys/class/power_supply/BAT1/capacity") as f:
    power_level = int(f.read())

icon = states[int(power_level / 10) % 10 - 1]
print(f"{icon}{power_level:>3}%")
