#!/bin/sh

git status
if [ -z "$(git status -s -uno | grep -v '^ ' | awk '{print $2}')" ]; then
  gum confirm "Stage all?" && git add . || exit
fi

TYPE=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" "chore" "revert")
SCOPE=$(gum input --placeholder "scope")

test -n "$SCOPE" && SCOPE="($SCOPE)"

SUMMARY=$(gum input --value "$TYPE$SCOPE: " --placeholder "Summary of this change")
DESCRIPTION=$(gum write --placeholder "Details of this change")

gum confirm "Commit changes?" && gum spin --title='Committing...' --show-output -- git commit -m "$SUMMARY" -m "$DESCRIPTION"
gum confirm "Push changes?" && gum spin --title='Pushing...' --show-output git push
