#!/bin/zsh
NAME=$1
ARTIST=$2
# gum spin --title "\x1b[33mSearching for $NAME by $ARTIST\x1b[0m" --show-output -- echo "$NAME by $ARTIST" | /mnt/DATA/scripts/lyrics.py
gum spin --title "Searching for $NAME by $ARTIST" --show-output -- zsh -c "echo $NAME by $ARTIST | /mnt/DATA/scripts/lyrics.py"
