#!/bin/sh
query="$@"
if [[ -z "$query" ]]; then
  firefox "https://www.google.com"
else
  encoded=$(echo "$query" | jq -sRr @uri)
  echo $encoded
  firefox "https://www.google.com/search?q=$encoded"
fi
