#!/bin/sh

SOCKET="$2"
MSG="$1"

{ [ -z "$MSG" ] || [ -z "$SOCKET" ]; } && {
  echo "usage: $0 <message> <sock_path>">&2
  exit 1
}

{
  printf "%08x" "${#MSG}" | xxd -r -p
  printf "%s" "$MSG"
} | socat - UNIX-CONNECT:$SOCKET
