#!/bin/sh

case "$1" in
prev)
  playerctl previous
  notify-send "MavenCore" "Previous" -i ~/Pictures/AVATAR -u low
  ;;
next)
  playerctl next
  notify-send "MavenCore" "Next" -i ~/Pictures/AVATAR -u low
  ;;
toggle)
  playerctl play-pause
  notify-send "MavenCore" "Toggled play/pause state" -i ~/Pictures/AVATAR -u low
  ;;
esac
