#!/usr/bin/env python3

import asyncio
import json
import os

SOCK = os.environ["NIRI_SOCKET"]

def display(data: str):
    data = data if len(data) < 35 else data[:34]+"…"
    print(data, flush=True)

async def main():
    reader, writer = await asyncio.open_unix_connection(SOCK)

    writer.write(json.dumps({"EventStream": None}).encode() + b"\n")
    await writer.drain()

    windows = {}

    while True:
        line = await reader.readline()

        if not line:
            break

        try:
            event = json.loads(line.decode())
        except:
            continue

        if "WindowsChanged" in event:
            windows = dict(((win['id'], win['title']) for win in event["WindowsChanged"]["windows"]))
            [display(win['title']) for win in  event["WindowsChanged"]["windows"] if win['is_focused']]

        if "WindowFocusChanged" in event:
            win_id = event["WindowFocusChanged"]['id']

            if win_id is None:
                name = "desktop"
            else: 
                name = windows[int(win_id)]

            display(name)

        if "WindowOpenedOrChanged" in event:
            win_id = event["WindowOpenedOrChanged"]["window"]['id']
            win_title = event["WindowOpenedOrChanged"]["window"]['title']
            win_active = event["WindowOpenedOrChanged"]["window"]['is_focused']

            windows[int(win_id)] = win_title

            if win_active:
                display(win_title)



if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
