#! /bin/zsh

run() {
  if [[ "$DESKTOP_SESSION" == "niri" ]]; then
    niri msg action spawn -- "$1"
  elif [[ "$DESKTOP_SESSION" == "hyprland" ]]; then
    hyprctl dispatch exec "$1"
  fi
}
if [[ "$1" == "waybar" ]]; then
  killall waybar
  run waybar
  echo ran

elif [[ "$1" == "hyprpaper" ]]; then
  killall hyprpaper
  run hyprpaper
fi
