#!/bin/bash

function run() {
  if [[ "$XDG_CURRENT_DESKTOP" == "niri" ]]; then
    niri msg action spawn -- "$@"
  elif [[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]]; then
    hyprctl dispatch exec "$@"
  fi
}

for i in $@; do
  killall $i
  run $i
  sleep 0.25
  notify-send MavenCore "Restarted $i" -i "/mnt/DATA/Pictures/AVATAR"
done
