#! /bin/env python3
from sys import argv

out = ""
sepd = True
for i in argv[1]:
    if i in [" ", "-", "_"]:
        sepd = True
    else:
        if sepd:
            sepd = False
            out += i.upper()
        else:
            out += i

print(out, end="")
