#!/usr/bin/env python3
import socket

try:
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
        s.connect(("8.8.8.8", 80))
        print(s.getsockname()[0])
except Exception as e:
    print(f"Error: {e}")
