#! /usr/bin/env python3

with open("/proc/uptime", "r") as f:
    uptime_seconds = float(f.readline().split()[0])


uptime_hours = int(uptime_seconds // 3600) % 24
uptime_days = int(uptime_seconds // 86400)
uptime_min = int(uptime_seconds // 60) % 60
uptime_seconds = int(uptime_seconds % 60)

uptime = f" {uptime_days:0>2}:{uptime_hours:0>2}:{uptime_min:0>2}:{uptime_seconds:0>2}"

print(uptime)
