#!/bin/bash

MONITOR="eDP-1"
LIVE=~/Pictures/CURRENT-LIVE
FRAME=~/Pictures/CURRENT-LIVE-FF
FLAG=/tmp/.wallpaper-live-off

if [[ $1 == "toggle-live" ]]; then
  if [[ -e "$FLAG" ]]; then
    # Enable live mode
    rm "$FLAG"
  else
    # Disable live mode
    touch "$FLAG"
    ffmpeg -y -i "$LIVE" -frames:v 1 /tmp/CLFF.png &&
      mv /tmp/CLFF.png "$FRAME"
  fi
fi

killall mpvpaper
if [[ -e $FLAG ]]; then
  nohup mpvpaper -o "--no-audio --loop --scale=nearest" "$MONITOR" "$FRAME" >/dev/null 2>&1 &
  notify-send "MavenCore" "Live wallpaper disabled"
else
  nohup mpvpaper -o "--no-audio --loop --scale=nearest" "$MONITOR" "$LIVE" >/dev/null 2>&1 &
  notify-send "MavenCore" "Live wallpaper enabled"
fi
