#! /bin/bash
if [[ $1 = "toggle-live" ]]; then
  if [[ -e /tmp/.wallpaper-live-off ]]; then
    rm /tmp/.wallpaper-live-off
    "$0"
  else
    touch /tmp/.wallpaper-live-off
    swww img ~/Pictures/CURRENT-LIVE-FF
  fi
else

  if pgrep swww-daemon; then
    pkill swww-daemon
    rm ~/Pictures/CURRENT-LIVE-FF
    sleep 1
  fi
  if ! grep ~/Pictures CURRENT-LIVE-FF; then
    ffmpeg -i ~/Pictures/WallpaperQueue/GreenCat.mp4 -frames:v 1 /tmp/CLFF.png && mv /tmp/CLFF.png ~/Pictures/CURRENT-LIVE-FF
  fi

  hyprctl dispatch exec "swww-daemon --no-cache"
  swww img ~/Pictures/CURRENT
  swww img ~/Pictures/CURRENT-LIVE
# ifmis => we blit the first frame and wait for the gif to load
fi
